# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: JavaScript Scraper

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
    - name: mkdir sites
      run: mkdir sites
    - name: Checkout External Repository
      uses: actions/checkout@v2
      with:
        repository: peviitor-ro/scrapers.js
        ref: main
        path: sites
    - name: Remove everything but the sites folder
      run: |
        find root/sites/ -mindepth 1 -maxdepth 1 ! -name 'sites' -exec rm -r {} \;
        mv root/sites/sites/* root/sites/
        rm -r root/sites/sites
    - name: ls sites
      run: ls sites
